# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :tf do
    increment_build_number(xcodeproj: "AddaMeIOS.xcodeproj")
    build_app(scheme: "AddaMeIOS")
    upload_to_testflight
  end

  desc "Push a new release build"
  lane :release do
    precheck
    increment_build_number(xcodeproj: "AddaMeIOS.xcodeproj")
    snapshot
    frameit
    deliver(
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: false,
      skip_binary_upload: true
    )
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "AddaMeIOS.xcodeproj", scheme: "AddaMeIOSUITests")
  end

  lane :sandbox do
    capture_screenshots
    frame_screenshots(white: true)
    frameit(path: "./fastlane/screenshots")
  end

  lane :submit_review do
    frame_screenshots(white: true)
    frameit(path: "./fastlane/screenshots")
    deliver(
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: false,
      skip_binary_upload: true
    )
  end
end
